### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by cecton** [wasmbl/wasmbl#34]
Right now it's not very obvious for the user what they are waiting for. It would be nice to have a log for when wasm-opt has finished downloading and one log for when the build has finishing during serving.

**Comment by fstephany** [comment]
As discussed in the draft PR, I'll go with `log`. Do I initialize it with `env_logger` or do we want to have a complete custom output? I personally think that regular logs will do the trick for now and if needed we add proper output?

**Comment by cecton** [comment]
You can probably add the code that initialize the default logger in the hook struct. So it will be default for everybody unless someone wants to do something fancy

**Comment by cecton** [comment]
I'm assigning this ticket to @YohDeadfall because it's an easy one to work on. I hope you don't mind :sweat_smile:
